### ISSUE TITLE
Usages in the core typechecker

### ISSUE THREAD

**Issue by andy-morris** [metastatedev/juvix#414]
When I was looking at the core typechecker earlier I noticed that it seems to check usages incorrectly. When moving into a subterm, it passes the whole context in and expects the subterm to match with the usages.

In other words, for something like an application `f s`, it expects everything to be used by both `f` *and* `s`, instead of one of the other.

I think the easiest-to-understand way to fix this is to count the usages during typechecking and ensure they are compatible with the context at the end. Since the last time I brought this up I have actually found a reference describing this idea in detail: [pdf](https://drops.dagstuhl.de/opus/volltexte/2018/10049/pdf/LIPIcs-TYPES-2017-1.pdf), [agda](https://github.com/gallais/typing-with-leftovers). For example the App rule becomes something like:

```
  Γ; Φ ⊢  σ f   :˃ (π x: A) → B ⊣ Ψ
  Γ; Ψ ⊢ πσ s   :˂ A            ⊣ Θ
------------------------------------
  Γ; Φ ⊢  σ f s :˃ B[x ≔ s]     ⊣ Θ
```

where:

- Γ contains just types
- Φ, Ψ, Θ contain just usages
- the usage context before ⊢ is an input, saying how many usages are available to this term, and the one after ⊣ is an output, saying how many are still left over *after* checking this term

The Var rule just subtracts the required usage from that provided:

```
----------------------------------------------------
  Γ, x: A, Δ; Φ, π x, Θ ⊢ σ x :˃ A ⊣ Φ, (π-σ) x, Θ
```

Everything else is probably more or less how you'd expect given these two.

(The Agda code I wrote a while ago does it a bit differently, but this way that TWL describes is even easier I think.)

**Comment by cwgoes** [comment]
Yes, that makes sense. Thanks for catching this.

**Comment by thealmarty** [comment]
Thanks. Yes the core type checker was not thoroughly tested. I moved on to something else before finishing it on the assumption that first class usage will be added and the type checker will be fixed then. So I think don't worry too much about fixing it? See [here](https://github.com/metastatedev/juvix/pull/237#issuecomment-584266663.).

**Comment by andy-morris** [comment]
Related: it seems to me that `typeElim` needs to take the expected usage as an input as well, since we want to possibly split the available usages into different sites, right?

For example: if we have `5 x: A` and `1 f: 2 A -> 3 A -> A` then we want the expression `f x x` to work, rather than, if I'm understanding the current code correctly, inferring `5 x: A` for the first occurrence of `x`, then failing with `2 ≠ 5`.

But I thought it'd be best to check if this sounds right to everyone else, of course.

**Comment by thealmarty** [comment]
What do you have in mind for the scope of the different sites? If you just mean locally within `let` then it makes sense to me.

**Comment by andy-morris** [comment]
@thealmarty They still have the same scope but as you go through the term you keep track of how many have been used up. So in this example:

- Infer the type of `f` with (let's say) a usage of `1`.
  - Get an answer of `2 A -> 3 A -> A`
  - Subtract `1` from the available usages of `f`, leaving `0 f` in the output context
- Check the first `x` against `A` and `2`.
  - Infer its type, getting `A`, which is of course a subtype of itself
  - Subtract `2` from the available usages of `x`, leaving `3 x` in the output context for this branch
- Check the second `x` against `A` and `3`
  - Same as above, ultimately leaving `0 x` in the output context

But this means you always need to know upfront the usage of each subterm, as far as I can tell, even when its type is inferrable.

**Comment by cwgoes** [comment]
> Related: it seems to me that typeElim needs to take the expected usage as an input as well, since we want to possibly split the available usages into different sites, right?

Yes, this seems right.

> But this means you always need to know upfront the usage of each subterm, as far as I can tell, even when its type is inferrable.

Hmm, hopefully we can ease the burden on the programmer (later) with usage unification/solving here.
