### ISSUE TITLE
How to contribute guidelines

### ISSUE THREAD

**Issue by awasunyin** [metastatedev/juvix#424]

**Comment by cwgoes** [comment]
Sounds like this may already be covered in https://github.com/metastatedev/juvix/pull/600.

Let's have someone from the community subteam check to make sure that it's clear.

**Comment by thealmarty** [comment]
Yes please let me know if the "Contributing" section of the Readme is clear. Thanks. @Asamartino

**Comment by Asamartino** [comment]
looks good to me
