### ISSUE TITLE
2 M's in ammount at the beginning of Page 18 of the language reference

### ISSUE THREAD

**Issue by sean-magin** [metastatedev/juvix#516]
Trying to help in any way I can :D 
<img width="1005" alt="Screen Shot 2020-09-17 at 3 58 30 PM" src="https://user-images.githubusercontent.com/14209806/93418582-dc528a80-f8fe-11ea-8de3-917cb9c4ca98.png">

**Comment by cwgoes** [comment]
Thanks! We'll fix that. Do note that the language reference is pretty out-of-date at the moment.

**Comment by sean-magin** [comment]
Yup no worries! And cool, thanks for the heads up. Are the readme instructions of the main repo the best guides to follow in order to start playing around with Juvix?

**Comment by cwgoes** [comment]
For now, yes; we're working on a website with documentation which will be published soon (tm).
